config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :users, only: [:index, :show, :new, :create]
  get 'projects/:id/statistics' => 'projects#statistics'
  resources :projects, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  get 'shares/' => 'shares#api'

  resources :purchases, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :shares
  has_many :purchases

  accepts_nested_attributes_for :shares

  validates :name, :description, :picture_url, :max_shares, presence: true
  validates :max_shares, numericality: {greater_than: 0}
  validate :valid_time


  def calculate_shares(status)
    shares_sold= Purchase.where(project_id: self.id).sum(:number_of_shares)

    if status == 'sold'
      return shares_sold
    elsif status == 'left'
      return self.max_shares - shares_sold
    end
  end

  def percentage
    self.calculate_shares("sold").to_f/self.max_shares*100
  end

  def days_left
    return ((self.deadline - DateTime.now.utc)/86400).floor
  end

  def valid_time
    if (self.deadline <= Time.now)
      errors.add(:valid_time, "is already passed")
    end
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :share

  validates :number_of_shares, :share_id, presence: true
  validates :number_of_shares, numericality: {greater_than: 0}
  validate :available_shares

  def available_shares
    project = Project.find(self.project_id)
    if self.share_id
      share_want = Share.find(self.share_id)
    else
      errors.add(:share_id, "not found. Select share")
      return
    end

    num_shares_want = self.number_of_shares
    max_shares_available_from_project = project.max_shares
    all_purchases = project.purchases
    total = 0
    all_purchases.each do |purchase|
        total += purchase.number_of_shares
    end

    if (total + num_shares_want) > max_shares_available_from_project
      errors.add(:number_of_shares, "not available. Try a smaller number.")
    end
  end
end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :project
  has_many :purchases

  validates :price, numericality: {greater_than: 0}
  validates :share_type, :price, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, presence: true

  has_many :projects
  has_many :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "You are not logged in, please log in to make a reservation"
      redirect_to new_session_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # if current_user
    #   redirect_to projects_path
    # end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :ensure_logged_in

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @purchase = Purchase.new
  end

  def new
    @project = Project.new
    @project.shares.build
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:notice] = "Project Updated Successfully"
      redirect_to project_path(@project)
    else
      flash[:alert] = "Project not successfully updated."
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def statistics
    # render :layout => false
    @project = Project.find(params[:id])
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :max_shares, :picture_url, :deadline, shares_attributes: [:price, :share_type, :_destroy])
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  before_action :ensure_logged_in

  def new
    @purchase = Purchase.new
  end

  def create
    puts "********"
    puts params
    @purchase = Purchase.new(purchase_params)
    @purchase.user_id = current_user.id
    if @purchase.save
      redirect_to projects_path
    else
      @project = Project.find(params[:purchase][:project_id])
      render 'projects/show'
    end
  end

  private
  def purchase_params
    params.require(:purchase).permit(:number_of_shares, :share_id, :project_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # render :layout => false
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to projects_path, notice: "Thanks for logging in!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "You have logged out."
  end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def api
    #sorry i'm a lazy guy I know i shouldn't be doing this here

    max = Project.find(params[:project_id]).max_shares
    share_types = Share.where(project_id: params[:project_id])
    arr = []
    list= []
    share_types.each do |share|
        object = {}
        number_of_shares = (Purchase.where(share_id: share.id).sum(:number_of_shares)*100.0/max).to_i
        object[:y] = number_of_shares.to_i
        object[:legendText] = share.share_type
        object[:label] = share.share_type
        arr << object
        list << (object[:y])
    end
    object = {}
    number_of_shares = 100-Project.find(params[:project_id]).percentage.to_i
    object[:y] = number_of_shares.to_i
    object[:legendText] = "Available"
    object[:label] = "Available"
    arr << object
    list << object[:y]
    max = list.max
    puts max


    arr.each do |x|
      if (x[:y]) == max
        x[:exploded] = true
      end
    end
    arr.map do |x|
      x.to_json
    end
  @list = arr
  render json: @list
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gofundyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300&subset=latin,greek' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="navigation-bar">
    <%= link_to "GoFundYourself", '/', class:"homeButton" %>
  <% if current_user %>
    <%= link_to "New Project", new_project_path, class:"viewProject" %><%= link_to "View Projects", projects_url, class:"viewProject" %><%= link_to 'View Profile', user_path(current_user), class:"viewProject" %> <%= link_to "Logout", session_path("this session"), class:"signUpButton", :method => :delete %>
  <% else %>
    <%= link_to "View Projects", projects_url, class:"viewProject" %><%= link_to "Log In", new_session_path, class:"loginButton" %> <%= link_to "Sign Up", new_user_path, class:"signUpButton" %>
  <% end %>
  </div>
  <% flash.each do |key, value | %>
    <div id='flash_message'><%= image_tag 'whitecheck.png', id: 'checkmark' %><%= value %></div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="home-background-login">
  <%= image_tag "GFY.jpg" %>
</div>
<div id='loginBackground'></div>
<div class="home-content">
    <h1 id="welcome-page">Have a great idea?  <span style=color:#00A08E>Share it.</span></h1>
    <p id="sub-header">GoFundYourself is an online platform for crowd funded ideas to grow into companies.  Create your own project, or help someone else's along.</p>

<% if current_user %>
  <a href="/projects" class="myButton">Get Started</a>
<% else %>
  <a href="/users/new" class="myButton">Get Started</a>
<% end %>
</div>

app/views/projects/_share_fields.html.erb
<link rel="stylesheet" href="/assets/projects.scss">

<div class='nested-fields' id='nested-fields-margin'>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, id:'user-box' %>
  </div>
  <div class="field">
    <%= f.label :share_type %><br>
    <%= f.text_field :share_type, id:'user-box' %>
  </div>
  <%= link_to_remove_association "remove share type", f %>
  <br><br>
</div>

app/views/projects/edit.html.erb
<h1 class="page-heading">Edit Project</h1>

<%= form_for @project do |f| %>
<div id='project-new-form'>
  <div class="form-field-project-new">
    <%= f.label :name %><br>
    <%= f.text_field :name, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :description %><br>
    <%= f.text_area :description, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :picture_url %><br>
    <%= f.text_field :picture_url, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :max_shares %><br>
    <%= f.number_field :max_shares, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline, :discard_hour => true, id: 'user-box' %>
  </div>
<div id='login-submit-div'><%= submit_tag "Edit Project", class:'login-submit-user' %></div>
</div>

<% end %>

app/views/projects/index.html.erb
<div class="page-body">

<h1 class="page-heading">All Projects</h1>
<% @projects.each do |project| %>
<div class="project-card">
  <%= link_to image_tag(project.picture_url), project_path(project), :id =>'viewProjectImage'%>
  <h1 class="project-name"><%= project.name %></h1>
  <div class="project-description"><%= project.description %></div>
  <%= link_to "See Project", project_path(project), class:"project-link" %>
</div>
<% end %>

</div>

app/views/projects/new.html.erb
<h1 class="page-heading">Create a Project</h1>


<%= form_for @project do |f| %>
<div id='project-new-form'>
  <div class="form-field-project-new">
    <%= f.label :name %><br>
    <%= f.text_field :name, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :description %><br>
    <%= f.text_area :description, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :picture_url %><br>
    <%= f.text_field :picture_url, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :max_shares %><br>
    <%= f.number_field :max_shares, id: 'user-box' %>
  </div>
  <div class="form-field-project-new">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline, :discard_hour => true, id: 'user-box' %>
  </div>
</div>

<h1 class="page-heading">Shares Available For Sale</h1>

    <%= f.fields_for :shares, html:{id: 'shares'} do |share| %>
      <%= render 'share_fields', f: share%>

    <div class="form-field-project-new">

      <%= link_to_add_association 'add share type', f, :shares, {class:'links'} %>

    <% end %>


  <%= submit_tag "Create Project" , id:'project-submit-div'%>

<% end %>

app/views/projects/show.html.erb
<div class="individualProductPageBody">

<%= link_to "Back to all projects", projects_path, class:"backToAllProjectsButton" %>
<h1 class="project-name-show"><%= @project.name %></h1>
<%= image_tag @project.picture_url, class:"individualProductPageImage" %>

<div class="keyProjectInfo">
<p class="project-max-shares-show"><%= @project.max_shares %></p> maximum shares
<p class="sharesAvailable"><%= @project.calculate_shares("left") %></p> shares available
<p class="daysToGo"><%= @project.days_left%></p> days to go
</div>


<h4 class="project-description-title-show">Description</h4>
<p class="project-description-show"><%= @project.description %></p>


<p class="sharesSold">Percentage of Shares Sold: <%= @project.percentage.round(1)%>%</p>
<p id="qwerty"><%= @project.percentage.round(1) %> </p>

  <div id="myProgress">
    <div id="myBar"></div>
  </div>


<script>
function move() {
    var elem = document.getElementById("myBar");
    var width = 1;
    var percent = document.getElementById("qwerty").textContent
    var id = setInterval(frame, 20);
    percent = parseInt(percent.slice(0,percent.length-1))
    function frame() {
        if (width >= percent) {
            clearInterval(id);
        } else {
            width++;
            elem.style.width = width + '%';
        }
    }
}
move();
</script>
<br>
<div class="pricePerShare"> Price Per Share ($US):<br><br>
<% @project.shares.each do |share| %>
<%= share.share_type %> @ <%= share.price %>$ per share <br>
<% end %>
</div>

<div class=purchaseForm>
<h2 class="purchaseFormTitle"> Purchase Shares </h2>
<%= form_for @purchase do |f| %>
<div class="numSharesOnForm"
<%= f.label :number_of_shares %>
<%= f.number_field :number_of_shares %>
<br>
<%= f.label :share_type %>:<br>
<div id='project-show-radio'>
<% @project.shares.each do |share| %>

<%= f.radio_button :share_id, share.id%> <%=share.share_type%><br>
<% end %>
</div>
<br>
<%= f.hidden_field :project_id, value: @project.id %>
<div class="purchaseButton">
  <%= f.submit "Purchase Shares"%>
<% end %>


</div>
</div>

</div>
<br><br><br><br><br>
<script type="text/javascript">
 $(function () {
  url = document.URL.split("/")

  $.ajax({
    method: 'GET',
    url: "/shares",
    data: {project_id: url[url.length-1]}
  }).done(function(response){
    var chart = new CanvasJS.Chart("chartContainer",
    {
      title:{
        text: "Breakdown of Share Types Purchased"
      },
      exportFileName: "Pie Chart",
      exportEnabled: true,
                  animationEnabled: true,
      legend:{
        verticalAlign: "bottom",
        horizontalAlign: "center"
      },
      data: [
      {
        type: "pie",
        showInLegend: true,
        toolTipContent: "{legendText}: <strong>{y}%</strong>",
        indexLabel: "{label} {y}%",
        dataPoints: response
    }
    ]
    });
    chart.render();
  })

  //ajax

})
</script>

<div id="chartContainer" style="height: 300px; width: 100%;"></div>

<div id="chartContainer" style="height: 300px; width: 100%;"></div>
</body>

app/views/projects/statistics.html.erb
  <!DOCTYPE HTML>
<html>

<head>
<script type="text/javascript">
window.onload = function () {
  var chart = new CanvasJS.Chart("chartContainer",
  {
    title:{
      text: "Top Categories of New Year's Resolution"
    },
    exportFileName: "Pie Chart",
    exportEnabled: true,
                animationEnabled: true,
    legend:{
      verticalAlign: "bottom",
      horizontalAlign: "center"
    },
    data: [
    {
      type: "pie",
      showInLegend: true,
      toolTipContent: "{legendText}: <strong>{y}%</strong>",
      indexLabel: "{label} {y}%",
      dataPoints: [
        {  y: 35, legendText: "Health", exploded: true, label: "Health" },
        {  y: 20, legendText: "Finance", label: "Finance" },
        {  y: 18, legendText: "Career", label: "Career" },
        {  y: 15, legendText: "Education", label: "Education"},
        {  y: 5, legendText: "Family", label: "Family" },
        {  y: 7, legendText: "Real Estate", label: "Real Estate"}
      ]
  }
  ]
  });
  chart.render();
}
</script>
<script type="text/javascript" src="/assets/javascripts/canvasjs.min.js"></script>
</head>
<body>
<div id="chartContainer" style="height: 300px; width: 100%;"></div>
</body>

</html>

app/views/purchases/new.html.erb
<%= link_to "Back to Projects", projects_path %>
<%= form_for @purchase do |f| %>
<h1 class="page-heading">Make a Transaction</h1>
  <div class="field">
      <%= f.label :number_of_shares %><br>
      <%= f.number_field :number_of_shares %>
  </div>
<% end %>

app/views/shares/show.html.erb
<h1><%= @share.num_shares %></h1>

app/views/users/new.html.erb
<div class="home-background-login">
  <%= image_tag "GFY.jpg" %>
</div>
<div id='loginBackground'></div>
  <div id='loginBox'>
    <a href='/sessions/new' id='background-tab-right-user'>Log In</a>
    <a href='/users/new' id='background-tab-left-user'>Sign Up</a>
    <%= form_for @user do |f| %>
      <div class='form-field-top'>
        <%= f.label :name %>
        <%= f.text_field :name , id:'user-box'%>
      </div>
      <div class="form-field">
        <%= f.label :email %><br>
        <%= f.email_field :email, id:'user-box' %>
      </div>
      <div class="form-field">
        <%= f.label :password %><br>
        <%= f.password_field :password , id:'user-box' %>
      </div>
      <div class='form-field'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, id: 'user-box' %>
      </div>

      <div id='login-submit-div'><%= submit_tag "Create Account" , class:'login-submit-user'%></div>

    <% end %>
  </div>

<%= link_to (image_tag 'Delete-50.png', id:'login-x'), root_path %>

app/views/users/show.html.erb
<div class="profile-info">
  <img class="profile-page-image" src="http://www.thebolde.com/wp-content/uploads/2015/11/iStock_000083903869_Small-400x400.jpg">
  <div class="profile-page-user-info">
    <h2 class="profile-page-name"><%= @user.name %></h2>
    <h3 class="profile-page-email"><%= @user.email %></h3>
  </div>
</div>

<h4 class="profile-page-titles">ALL PROJECTS ( <%= @user.projects.count %> )</h4>
<div class="profile-page-projects">
  <% @user.projects.each do |project| %>
      <div class="profile-page-project">
      <a href="/projects/<%= project.id %>"><img class="project-image" src="<%= project.picture_url %>" alt=""></a>
      <h1 class="project-name-class"><%= project.name %></h1>
      <h1 class="project-funded"><%= project.percentage.round(1) %>% funded</h1>
      <h1 class="project-shares-total"><%= project.calculate_shares('left') %> Shares Left</h1>
      <h1 class="project-days-togo"><%= project.days_left %> Days left</h1>
      <h1 class="edit-project"><%= link_to "(Edit Project)", edit_project_path(project), class:"edit-project-link"%></h1>
    </div>
  <% end %>

</div>
<h4 class="profile-page-titles">PURCHASES (<% count = 0
  @user.purchases.each do |purchase|
     count += purchase.number_of_shares
   end %>
   <%= count %>
)</h4>
<div class="profile-page-purchases">
  <% @user.purchases.each do |purchase| %>
    <div class="profile-page-purchase">
      <h1 class="purchase-project"><%= purchase.project.name %> <%= link_to "(See Project)", project_path(purchase.project.id), class:"profile-project-link" %></h1>
      <h1 class="purchase-num-shares"><%= purchase.number_of_shares %> shares bought | Market Value $<%= (purchase.share.price) * purchase.number_of_shares %></h1>
    </div>
    <hr class="profile-page-divider">
  <% end %>